### PR TITLE
added norm call with two mats

### PR DESCRIPTION
**Pull request by netbrain**

### CODE REVIEW

**Comment by deadprogram** [comment]
Just wondering if perhaps this should be named `NormWithMats()`

What do you think @netbrain ?

**Comment by netbrain** [comment]
I really dont have a preference. You are free to call it.

**Comment by deadprogram** [comment]
OK, can you please change to `NormWithMats()` then? Thank you very much!

**Comment by deadprogram** [comment]
Also, please rebase again against the `dev` branch. Thanks!

**Comment by deadprogram** [comment]
Pinging Dr. @netbrain any chance for getting this PR updated so it can land? Thank you.

**Comment by netbrain** [comment]
@deadprogram finally picked up the ball on this and renamed the functions. Sorry it took it's sweet time! Anyways should be OK now, I think. :1st_place_medal:

**Comment by deadprogram** [comment]
Thanks for making the requested changes @netbrain now squash/merging.

**Pull request merged**
