### PR TITLE
correct the argument varaible name

### PR DESCRIPTION
**Pull request by superryanguo**
Hi, I just found the argument names(proto and model) in the cmd/dnn-pose-detection/main.go might be wrong, so this commit was pushed.

### CODE REVIEW

**Comment by superryanguo** [comment]
appveyor built pass and circleci failed, anybody know why? I checked the log in circleci, and looks more like a env issue, how to handle such issue? @repo admin

**Comment by superryanguo** [comment]
Post more info here for the built failed, appveyor is using the model file in "set GOCV_ONNX_TEST_FILES=C:\opencv\testdata", while for circleci, it install from "curl -sL https://github.com/onnx/models/blob/master/vision/classification/inception_and_googlenet/googlenet/model/googlenet-9.onnx\?raw\=true > /usr/local/go/src/github.com/hybridgroup/gocv/testdata/googlenet-9.onnx
", so there might some update from google net? I think might a baseline issue, @deadprogram @drnic @lstep

**Comment by deadprogram** [comment]
The primary branch of the onnx repo was renamed to `main`, but I think that happened a while ago already.

The error from the CircleCI build is:

```
onnx_importer.cpp:102: error: (-210:Unsupported format or combination of formats) Failed to parse onnx model from in-memory byte array. in function 'ONNXImporter'
```

In any case, the changes in this PR have no impact on the test suite, so certainly seems entirely unrelated. I will look into the CI fail. Thanks!

**Comment by superryanguo** [comment]
thanks @deadprogram

**Comment by deadprogram** [comment]
Thanks for the corrections @superryanguo now merging.

**Pull request merged**
