### PR TITLE
contrib/face: extra setters and getters for LBPHFaceRecognizer

### PR DESCRIPTION
**Pull request by diegohce**
Just added some extra getters and setters to LBPHFaceRecognizer I thought might be helpful.

Cheers!

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @diegohce thank you for the addition.

Could you please add smoke test for the new functions? See https://github.com/hybridgroup/gocv/blob/release/CONTRIBUTING.md#how-to-add-a-function-from-opencv-to-gocv for details.

Thanks!

**Comment by diegohce** [comment]
Hi!
Yes, for sure. Look, I read the contribution doc and the excitement got me.
That's why the las PR do have smoke tests.

Will do today for sure. Thank for taking the time.

Cheers, Diego

**Comment by deadprogram** [comment]
> the excitement got me.

:heart:

**Comment by deadprogram** [comment]
> Will do today for sure. Thank for taking the time.

Thanks to you!

**Comment by deadprogram** [comment]
Thank you @diegohce now squashed/merged.

**Pull request merged**
