### PR TITLE
Add contrib/aruco

### PR DESCRIPTION
**Pull request by redben**
- [ ] cv::aruco::calibrateCameraAruco
- [ ] cv::aruco::calibrateCameraCharuco
- [ ] cv::aruco::detectCharucoDiamond
- [x] cv::aruco::detectMarkers
- [ ] cv::aruco::drawAxis
- [ ] cv::aruco::drawCharucoDiamond
- [ ] cv::aruco::drawDetectedCornersCharuco
- [ ] cv::aruco::drawDetectedDiamonds
- [x] cv::aruco::drawDetectedMarkers
- [x] cv::aruco::drawMarker
- [ ] cv::aruco::drawPlanarBoard
- [ ] cv::aruco::estimatePoseBoard
- [ ] cv::aruco::estimatePoseCharucoBoard
- [ ] cv::aruco::estimatePoseSingleMarkers
- [ ] cv::aruco::generateCustomDictionary
- [ ] cv::aruco::getBoardObjectAndImagePoints
- [x] cv::aruco::getPredefinedDictionary
- [ ] cv::aruco::interpolateCornersCharuco
- [ ] cv::aruco::refineDetectedMarkers
- [ ] cv::aruco::testCharucoCornersCollinear

### CODE REVIEW

**Comment by redben** [comment]
Nice, PR #880 adds Points2fVector among other things. I'll revert changes to core once that PR is merged.

**Comment by redben** [comment]
@deadprogram I added the basic functions for aruco, it this ok or would you prefer to cover everything in this PR?

**Comment by deadprogram** [comment]
Hello @redben thank you very much for working on this.

> I added the basic functions for aruco, it this ok or would you prefer to cover everything in this PR?

I think it would be great to add the current set of functions, and then add more features in additional pull request(s).

I see that the Appveyor tests are failing on Windows. Based on the message displayed, you probably need to add aruco to the `cgo.go` files such as https://github.com/hybridgroup/gocv/blob/dev/contrib/cgo.go#L11

Also, you probably want to squash your commits before merge? We can do this for you if you prefer. :smile_cat: 

Thanks!

**Comment by redben** [comment]
@deadprogram commits squashed and LDFLAGS updated 👍

**Comment by deadprogram** [comment]
Somewhat large PR, which even still only adds part of this feature set. Wow, amazing effort @redben thank you!

Now merging.

**Pull request merged**
