### PR TITLE
Feature/core

### PR DESCRIPTION
**Pull request by kylycht**
PR adds:
- Vconcat(Mat src1, Mat src2, Mat dst)
- Rotate(Mat src, Mat dst, int rotateCode)

### CODE REVIEW

**Comment by kylycht** [comment]
@deadprogram missed it, test added

**Comment by deadprogram** [comment]
Thank you @kylycht test looks good. I just noticed that both of these functions are actually in the 'core` module. Perhaps you would not mind moving `Rotate` into `core.go` etc.? Sorry I did not realize that before on my last feedback.

Thanks again for contributing!

**Comment by kylycht** [comment]
@deadprogram sure, added everything to core module(squashed commits as well)

thanks for the great repo!

**Comment by deadprogram** [comment]
Thanks @kylycht now merging.

**Pull request merged**
