### PR TITLE
Add opencv's 'MinEnclosingCircle' function to gocv (and test).

### PR DESCRIPTION
**Pull request by jonathankarsh**
Addressing part of #342

### CODE REVIEW

**Comment by jonathankarsh** [comment]
Notes:
1. Not sure about the new struct.
2. Perhaps a "global" const epsilon for the test isn't desired.
3. It seems that minEnclosingCircle is pretty unique in getting parameters by &ref, maybe that warrants a comment or different handling.
4. Forgot to add comment for new method, will do after first review / sanity check.

**Comment by deadprogram** [comment]
Hello @jonathankarsh thank you for the PR.

No need for the new struct, you can just use this signature instead 

```go
func MinEnclosingCircle(points []image.Point) (x, y, radius float32)
```

Also agree, please move the `epsilon` into the body of the test itself as a `var`

`cv::minEnclosingCircle()` is pretty typical of functions in OpenCV (and C++ in general) that return more than one value, generally do so by using params passed by pointer reference.

Yes, please add the GoDoc formatted comment like the other GoCV functions to the new function https://github.com/hybridgroup/gocv/pull/401/files#diff-50cee154353ca3af045f08401c7d081bR339

Lastly, should this type be defined in `core.go` possibly?
https://github.com/hybridgroup/gocv/pull/401/files#diff-50cee154353ca3af045f08401c7d081bR329

Thanks!

**Comment by jonathankarsh** [comment]
Thanks! PTAL

**Comment by deadprogram** [comment]
Looking good now, thanks for making those changes @jonathankarsh 

Now merging, thank you again for contributing.

**Pull request merged**
