### PR TITLE
Adding InScalarRange and NewMatFromScalarWithSize functions

### PR DESCRIPTION
**Pull request by milosgajdos83**
This commit adds two functions which help when dealing with `Scalar`s:
* `InScalarRange(src Mat, lb, ub Scalar, dst *Mat)`
* `NewMatFromScalarWithSize(s Scalar, rows int, cols int, mt MatType) Mat`

OpenCV C++ API allows to pass in `Scalar` to `cv::inRange` thanks to C++ templating capabilities, however due to the lack of generics and/or function overloading in `Go` I had to add a separate function (`InScalarRange`) to make the same functionality available in core `gocv` API

In order to make some useful operations on images using simpler code (as reported in #159) `NewMatFromScalarWithSize` allows to create a new `Mat` from a specified `Scalar` with specified dimensions.

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @milosgajdos83 thanks for the PR. Looks good, my only real comment is that I think the function should probably be named `InRangeWithScalar()` to help those performing a search in GoCV GoDocs for "inrange".

What do you think?

**Comment by milosgajdos83** [comment]
Excellent point @deadprogram - makes perfect sense.

I've now renamed the function as per your recommendation.

**Comment by deadprogram** [comment]
Thanks, that looks good @milosgajdos83 

Just one more thing... I wonder if perhaps you should change `NewMatFromScalarWithSize' to be `NewMatWithSizeFromScalar" anf then match the params order to be same as https://docs.opencv.org/3.4.1/d3/d63/classcv_1_1Mat.html#a3620c370690b5ca4d40c767be6fb4ceb

**Comment by milosgajdos83** [comment]
Great attention to detail @deadprogram 

Changed the names -- really should have thought of that myself in the previous commit.

Cheers.

**Comment by deadprogram** [comment]
Thanks @milosgajdos83 for indulging me. Now merging.

**Pull request merged**
