### PR TITLE
Add tracking legacy

### PR DESCRIPTION
**Pull request by Danile71**
DNM, please
After resolving https://github.com/opencv/opencv/issues/19260 I will test it

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @Danile71 looks like https://github.com/opencv/opencv/issues/19260 was merged and just released as part of OpenCV 4.5.2.

**Comment by Danile71** [comment]
@deadprogram, Oh, ok, I will test patch.

**Comment by deadprogram** [comment]
Thanks!

**Comment by deadprogram** [comment]
I suggest rebase from the `dev` branch which now has OpenCV 4.5.2

**Comment by Danile71** [comment]
@deadprogram, I added 452 to legacy/cgo.go

**Comment by deadprogram** [comment]
Small problem, this should have been against `dev` not `release` branch. So the same changes as the last commit are already in the `dev` branch.

**Pull request closed without merging**
