### PR TITLE
Update ROADMAP.md by removing scaleAdd

### PR DESCRIPTION
**Pull request by toffentoffen**
Update ROARDMAP.md as scaleAdd has been alrady implemented in #343.

### CODE REVIEW

**Comment by deadprogram** [comment]
The pattern I have been using is to mark features with an `X` once it lands in the `dev` branch, then to remove after it makes it into a release aka `master`. That way if someone looks at the `dev` branch they can figure out what is available but not yet released. 

This info should probably be added to the CONTRIBUTING.md, my bad.

**Comment by toffentoffen** [comment]
makes total sense @deadprogram. The problem is that this function is already in master, therefore I just removed the line. We didn't update properly the file last year when pr #343

**Comment by toffentoffen** [comment]
Done @deadprogram can be merged :smile:

**Comment by deadprogram** [comment]
Thank you! Now merging.

**Pull request merged**
