### PR TITLE
Add Matrix initializers: eye, ones, zeros

### PR DESCRIPTION
**Pull request by OmriTreidel**
Following issue [244](https://github.com/hybridgroup/gocv/issues/244) here are a few useful Matrix initializers.

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @OmriTreidel thank you for the contribution.

Can you please add godocs comments to the new functions? Similar to this https://github.com/hybridgroup/gocv/blob/release/core.go#L287-L291

**Comment by OmriTreidel** [comment]
@deadprogram  I've added the documentation. The build fails due to some circleCI configuration.

**Comment by deadprogram** [comment]
You need to rebase against the `dev` branch, @OmriTreidel if you please. Thanks.

**Comment by OmriTreidel** [comment]
@deadprogram  I've created a new branch and a new PR instead of this one #758

**Comment by deadprogram** [comment]
Thanks @OmriTreidel now closing this one.

**Pull request closed without merging**
