### PR TITLE
implemented getRectSubPix wrapper

### LINKED ISSUE #511: Add cv::getRectSubPix() binding
I need to use `cv::getRectSubPix()` method which retrieves a pixel rectangle from an image with sub-pixel accuracy.

Since there are no such a binding and PR's are gladly accepted, I have implemented this one.

### PR DESCRIPTION
**Pull request by awskii**
Fixes #511.

### CODE REVIEW

**Comment by awskii** [comment]
Not sure about tests but seems like there are no test for other wrappers in `imgproc.go` so i did not implement any.

**Comment by deadprogram** [comment]
We're you referring to https://github.com/hybridgroup/gocv/blob/master/imgproc_test.go ?

**Comment by deadprogram** [comment]
Also, all PRs need to made against the `dev` branch as mentioned in our contribution guidelines here:
https://github.com/hybridgroup/gocv/blob/master/CONTRIBUTING.md#how-to-use-our-github-repository

Thank you!

**Comment by awskii** [comment]
Sorry, will add test and resubmit PR against dev branch later. seems that PR could be closed, right?

**Comment by deadprogram** [comment]
You can also rebase against dev and squash your PRs commits, whichever you find is easier.

**Comment by twatzl** [comment]
Hey. I just discovered your MR and used it to build my own version of gocv since I need getRectSubPix.
Nice work! One thing i noticed though ist that all the other gocv functions have the parameters in the order
```
func Example(src Mat, dst *Mat, ...)
```
while your proposal for getRectSubPix has
```
func GetRectSubPix(src Mat, ..., dst *Mat, ...)
```

I don't know if it is an OpenCV thing, since this is one of the few functions which actually has a destination matrix as parameter, however from a users point of view I would find it more convenient and logical if all the gocv functions had src and dst as their first two parameters.

**Comment by awskii** [comment]
@twatzl another PR with tests has been already merged. Watch that for details https://github.com/hybridgroup/gocv/pull/532

**Pull request closed without merging**
