### PR TITLE
Update links in caffe-classifier demo

### PR DESCRIPTION
**Pull request by willdurand**
I wanted to try this demo and the links were outdated.

Maybe we could host these files in a separate repo?

### CODE REVIEW

**Comment by deadprogram** [comment]
You verified that the sample runs correctly with these files?

**Comment by willdurand** [comment]
> You verified that the sample runs correctly with these files?

yup, it does. `prototxt` is the same file and the other one has a different name but I found it in the updated opencv doc.

**Comment by deadprogram** [comment]
OK, thanks for the update.

**Comment by willdurand** [comment]
you're welcome :)

**Pull request merged**
