### PR TITLE
Add more functions used for stereo image processing.

### PR DESCRIPTION
**Pull request by michaelarusso**

### CODE REVIEW

**Comment by michaelarusso** [comment]
I haven't had time to write full unit tests for these new bindings I've added, but they are pretty much pass through directly to opencv. I have tested the functionality when some internal end to end tests between an original cpp implementation and the same implementation in Go using GoCV and these work fine.

Let me know if there are any questions!

**Comment by deadprogram** [comment]
@michaelarusso this looks great. Just needs some smoke tests to merge, as you know they do not need to be comprehensive, just touching the code changes is sufficient.

**Comment by michaelarusso** [comment]
@deadprogram I added the smoke tests plus an additional one for the MinMaxLoc func that pre-existed without a test. The AppVeyor build failed and seems unrelated to my change(some flaky test?). I'm not sure how to re-trigger the build without pushing another commit.

**Comment by deadprogram** [comment]
I just restarted Appveyor build...

**Comment by deadprogram** [comment]
Thank you very much @michaelarusso now merging.

**Pull request merged**
