### PR TITLE
Use opencv4 on Windows

### PR DESCRIPTION
**Pull request by mattn**
I'm thinking gocv should use pkg-config always on Windows too. We can fix dependencies without modify code.

### CODE REVIEW

**Comment by deadprogram** [comment]
I like this idea in theory. How do you install pkg-config for mingw-w64?

https://ci.appveyor.com/project/deadprogram/gocv/builds/23667840#L55

**Comment by mattn** [comment]
If you don't mind pkg-config clone, `go get github.com/mattn/pkg-gonfig/pkg-config

**Comment by mattn** [comment]
Test is passed on AppVeyor.

**Comment by mattn** [comment]
Can you provide way to use pkg-config on Windows too?

**Comment by mattn** [comment]
@deadprogram On Windows, we have to keep older version of OpenCV. (like opencv_dnn420) 
Could you provide way to use pkg-config?

**Comment by mattn** [comment]
I'm thinking you've better to switch to use msys2/mingw64 for OpenCV4 on Windows since msys2/mingw64 provide pkg-config. If gocv remove the specifying cgo directive on Windows, you will be maintenance free for the versions of OpenCV4 on Windows.

**Pull request closed without merging**
