### PR TITLE
BatchDistance BorderInterpolate CalcCovarMatrix CartToPolar

### PR DESCRIPTION
**Pull request by berak**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @berak thank you for another cool contribution. Could you please merge and resolve the merge conflict introduced by other recent changes to `core_test.go`. Thank you.

**Comment by berak** [comment]
conflicts resolved.

**Comment by deadprogram** [comment]
Thanks! Now merging.

**Comment by berak** [comment]
sorry, that it took so long

**Pull request merged**
