### PR TITLE
TestTrackbarWithValue fix

### PR DESCRIPTION
**Pull request by diegohce**
test was failing on opencv layer deprecation

### CODE REVIEW

**Comment by deadprogram** [comment]
> test was failing on opencv layer deprecation

Sorry, I didn't quite understand that comment? :smile_cat: 

I do not see any CI failures from that test.

**Comment by diegohce** [comment]
Hi!
I've sent a PR to fix a test on dev branch

**Comment by deadprogram** [comment]
I don't see any current failure on `dev` branch:

https://github.com/hybridgroup/gocv/actions?query=branch%3Adev

(note updated link)

**Comment by diegohce** [comment]
Closing due a misunderstood test message.

**Pull request closed without merging**
