### PR TITLE
CompleteSymm ConvertScaleAbs CopyMakeBorder Dct

### PR DESCRIPTION
**Pull request by berak**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @berak  this PR is also affected by the merge conflict from changes to `core_test.go`. Thank you.

**Comment by berak** [comment]
yea, took a while ;)

**Comment by deadprogram** [comment]
Thanks! Now merging.

**Comment by deadprogram** [comment]
Seems like still merge conflict here?

**Comment by berak** [comment]
moved the additions to core_batch3, to avoid further merge conflicts, will close this instead

sorry for all the noise, again.

**Pull request closed without merging**
