### PR TITLE
added TrackerGOTURN (see roadmap)

### PR DESCRIPTION
**Pull request by diegohce**
added TrackerGOTURN (see roadmap)

Not sure what to do with two model files needed to run the tests.

### CODE REVIEW

**Comment by diegohce** [comment]
missing files can be downloaded from here

https://github.com/opencv/opencv_extra/tree/c4219d5eb3105ed8e634278fad312a1a8d2c182d/testdata/tracking

for me, for the tests to work they had to be placed on the project's root dir.

**Comment by diegohce** [comment]
I have been experimenting in another repo with this https://git-lfs.com/

and it works like a charm.

Tried to push an experimental branch to my fork with that, but it didn't work as expected (maybe because is a fork? I don't know).

**Comment by deadprogram** [comment]
You probably want to look at https://github.com/hybridgroup/gocv/blob/dev/.github/workflows/linux.yml#L21-L29 for an example of how this sort of thing is being done currently.

**Comment by diegohce** [comment]
> You probably want to look at https://github.com/hybridgroup/gocv/blob/dev/.github/workflows/linux.yml#L21-L29 for an example of how this sort of thing is being done currently.

I'll take a look. Thanks!

**Comment by diegohce** [comment]
I'm sorry, Windows action is beyond my capabilities.

**Comment by deadprogram** [comment]
Hello @diegohce please take a look at my changes from yesterday to the CI tests now in the `dev` branch.

And let me know if you want my help on the testing for this PR.

Thank you!

**Comment by diegohce** [comment]
> Hello @diegohce please take a look at my changes from yesterday to the CI tests now in the `dev` branch.
> 
> And let me know if you want my help on the testing for this PR.
> 
> Thank you!

What I don't know for the windows CI to run properly is: what's gocv's root path? 
because there's where this caffe model files should be unzziped.

**Comment by deadprogram** [comment]
Hello @diegohce looks like something off about this PR with a bunch of extra commits? The core commits of the PR itself seem pretty good.

What do you think? `git cherry-pick` on a new branch off of `dev` maybe?

**Comment by diegohce** [comment]
> Hello @diegohce looks like something off about this PR with a bunch of extra commits? The core commits of the PR itself seem pretty good.
> 
> What do you think? `git cherry-pick` on a new branch off of `dev` maybe?

@deadprogram I will close this PR and send a cleaner one.

**Pull request closed without merging**
