### PR TITLE
Add Xphoto contrib

### PR DESCRIPTION
**Pull request by Syd76**
Xphoto contrib :

On TESTING for Inpaint functions, there an 

>fatal error: unexpected signal during runtime execution
>[signal SIGSEGV , segmentation vialotion code=0x1 addr=0X01.... ]

But, an application run well ( see : cmd/xphoto/main.go)

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @Syd76 thank you very much for this contribution.

I think you need to add `-lopencv_xphoto452` to the list of libs linked by Windows here: https://github.com/hybridgroup/gocv/blob/dev/contrib/cgo.go#L11

Since Windows does not have pkg-config support generally, all libs need to be in this list to be correctly linked.

**Comment by Syd76** [comment]
> I think you need to add `-lopencv_xphoto452` to the list of libs linked by Windows here: https://github.com/hybridgroup/gocv/blob/dev/contrib/cgo.go#L11

Yep, sorry i didn't see this wrong AppVeyor result.
I work only under Linux/ubuntu.

**Comment by Syd76** [comment]
[79f5a35](https://github.com/hybridgroup/gocv/pull/844/commits/79f5a35525c448f2ea90557bdf43fd1fa38f2c53)

- Change in order to be consistent with the Opencv function (parameter by reference)

**Comment by deadprogram** [comment]
Thanks for the changes @Syd76 I think it is looking good.

Would you mind squashing the commits so I can merge? Or I can do it if you prefer.

**Comment by deadprogram** [comment]
I will squash/commit now. Thank you very much for the awesome contribution @Syd76

**Pull request merged**
