### PR TITLE
Add openvino async

### PR DESCRIPTION
**Pull request by Danile71**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @Danile71 thank you for the PR. Just wondering if the files would be better named `dnn_async_openvino.go` etc. since this is functionality that only works with openvino.

Since it is part of the dnn module, I can see why you would not want to put into the `openvino` subpackage.

Anyhow, what do you think?

**Comment by Danile71** [comment]
Hi, @deadprogram,  I tried to place *async to another packer (openvino).
But `func (net *Net) ForwardAsync(outputName string) AsyncArray` must be in package gocv (net *gocv.Net not working)

**Comment by Danile71** [comment]
@deadprogram, you are right)

**Comment by deadprogram** [comment]
Shoudn't `asyncarray.cpp` be named `dnn_asyncarray_openvino.cpp`
`asyncarray.go` be named `dnn_asyncarray_openvino.go`, and so on for the rest of the newly added files?

**Comment by Danile71** [comment]
`opencv2/core/async.hpp`
It is "core" in official sources opencv, not dnn

**Comment by deadprogram** [comment]
OK, fair enough. Now merging, thank you!

**Pull request merged**
