### PR TITLE
Fix #761

### LINKED ISSUE #761: Compile error on Raspberry Pi OS 32bit
## Description
```
pi@raspberrypi:~/go/src/gocv.io/x/gocv $ go run ./cmd/version/main.go 
# gocv.io/x/gocv
./core.go:2009:16: type [1073741824]*_Ctype_char larger than address space
./core.go:2009:16: type [1073741824]*_Ctype_char too large
```

The line goes like this:
```
tmpslice := (*[1 << 30]*C.char)(unsafe.Pointer(strs.strs))[:length:length]
```
And the fix is trivial,
```
tmpslice := (*[1 << 28]*C.char)(unsafe.Pointer(strs.strs))[:length:length]
```
As far as I can tell, it doesn't cause any problems, but I tested this in a limited capacity. Should I send a PR to address this?

## Your Environment

* Operating System and version:
Raspberry Pi OS
Version: August 2020
Release date: 2020-08-20
* OpenCV version used:
gocv version: 0.25.0
opencv lib version: 4.5.0
* How did you install OpenCV?
I ran the `make install` script, per website instructions.
* GoCV version used:
0.25.0
* Go version:
go version go1.15.3 linux/arm
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?
No
* Hardware platform
Raspberry Pi 3

### PR DESCRIPTION
**Pull request by dlsniper**
This will allow compilation on 32bit Raspberry Pi OSes.

Fixes  #761.

### CODE REVIEW

**Comment by freman** [comment]
Alternatively

either arch files/build flags ala `core_arm.go` and `core_other.go`

```
// +build arm
```
```
// +build !arm
```
(https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool)

or check

```
const is64Bit = uint64(^uintptr(0)) == ^uint64(0)

maxSize := 27
if is64Bit {
maxSize = 30
}
```
Or something

But either way 👍

**Comment by deadprogram** [comment]
Thanks for the contribution @dlsniper now merging.

**Comment by jschank** [comment]
Hello,
Any timeline for when this patch will be released?

**Comment by deadprogram** [comment]
Very soon. Currently working on compatibility with the new OpenCV 4.5.1 then we will cut a release.

**Pull request merged**
