### PR TITLE
Addition of MOG2/KNN constructor with options

### PR DESCRIPTION
**Pull request by netbrain**
Hi guys! this is my first contribution to this project and I wanted to ensure that this code is correct in terms of the contributions guideline. So a little hand holding would be appreciated.

This change simply adds the the ability to change the default options that are set using the default MOG2 & KNN constructor.

Cheers!

### CODE REVIEW

**Comment by netbrain** [comment]
@deadprogram Hi, is it ok if i ask you for a code review?

**Comment by deadprogram** [comment]
Hello, @netbrain thank you very much for the PR. I think you have the correct idea about what needs to be included. Two things I would suggest:

- Please always include the link to the OpenCV function that is being wrapped. For example https://github.com/hybridgroup/gocv/blob/0addb2293f9051055074fde2842f38c98ac7b36c/video.go#L20-L22 this makes it a lot easier for people to navigate from the GoDocs to the correct OpenCV docs.
- It probably would be best to have slightly more "atomic" PRs. Once you update your comments, I will be "squashing and committing" this PR, since there are multiple commits needed to achieve the desired code state. Hopefully that makes sense. No need to spilt this PR, I am just suggesting a bit of guidance for the next one. :)

**Comment by netbrain** [comment]
Tank you @deadprogram, i thought as much myself. Ive gone and squashed it for you and also added the missing links to the actual function that my and the existing code calls.

Should be in tip top shape now i guess!

**Comment by deadprogram** [comment]
Looks great, thanks for the changes. Now merging.

**Pull request merged**
