### PR TITLE
Make toByteArray safe for empty byte slices

### PR DESCRIPTION
**Pull request by denismakogon**
Closes: #187

### CODE REVIEW

**Comment by denismakogon** [comment]
Hey (@deadprogram), Rob! What should i do with codecov checks?

**Comment by denismakogon** [comment]
yes, correct.

**Comment by deadprogram** [comment]
Hi @denismakogon can you please add a test for the empty array case you just added code to protect from? Thank you!

**Comment by deadprogram** [comment]
Thanks for adding the extra test, @denismakogon now merging.

**Pull request merged**
