### PR TITLE
Fix package names for CentOS 7 and Fedora 28

### PR DESCRIPTION
**Pull request by justinclift**
The present Makefile has a typo in the (RPMS) package name, for CentOS 7 and Fedora 28.

This PR fixes that, and also addresses the wget problem in #282. :smile:

It also adds `unzip` to the package list for CentOS and Fedora, as that's needed and isn't part of the general base system.

### CODE REVIEW

**Comment by justinclift** [comment]
Just checked on Fedora 28... and the package name there is `pkgconf-pkg-config` instead.

So, this PR needs adjusting.  It'll address that shortly.

**Comment by justinclift** [comment]
Btw, tested the changes on both Fedora 28 and CentOS 7.  These work as intended on both.

CentOS 7 still needs further work, but it's not stuff related to this. :smile:

**Comment by justinclift** [comment]
Hmmm, it'd probably be better to add both `unzip` and `wget` to the package list too, as neither of those are part of the minimal build.  On the other hand, it should be `curl` instead of `wget` anyway, as `curl` is part of the base system.

Just added a commit for that.  Someone using Debian/Ubuntu will probably want to check the `curl` command on their system though, just to see if it's part of the base install.  I'm not sure. :wink:

**Comment by deadprogram** [comment]
Thanks for all this great stuff, @justinclift I will test the Debian stuff and get back to you shortly.

**Comment by deadprogram** [comment]
OK, confirmed that it works on Ubuntu. This is terrific, thanks again for working on it @justinclift now merging.

**Comment by justinclift** [comment]
No worries at all @deadprogram. :smile:

**Comment by justinclift** [comment]
As a general observation, on CentOS 7 the standard gcc available (4.8.x) doesn't do enough C++11.  So, the `cmake` fails.

The workaround I used was to install the (official) "Developer Toolset 7" from the (Red Hat backed) "Software Collections" project:

&nbsp; &nbsp; https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/

That supplies a newer gcc among other things, so the `cmake` passes and things work.

I'm not sure if that's how everyone else using OpenCV on CentOS 7 is doing it though, so I haven't turned that into docs or steps for people to follow (which I often do).  On that note, there's no wiki here.  Is there some place to write down steps for other people to leverage, or is that more the kind of thing that goes into the book you're doing. :smile:

**Comment by deadprogram** [comment]
At the moment that kind of info has just been getting put into the README and then the gocv.io web site pages. A PR adding it seems like a good idea and would be appreciated.

**Comment by justinclift** [comment]
Oh, as a side thought... do you reckon turning on the wiki would be useful for people?

**Comment by deadprogram** [comment]
I thought about it, but I think at the moment we are better off updating the web site via PRs at https://github.com/hybridgroup/gocv-site

**Comment by justinclift** [comment]
No worries at all. :smile:

**Pull request merged**
